# Generated by Django 3.2 on 2024-04-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinmatchup',
            name='isWinner',
            field=models.BooleanField(null=True),
        ),
    ]
