# Generated by Django 3.2 on 2024-04-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join_tournament', '0004_alter_tournamentplayer_tournament'),
        ('tournament_details', '0002_playerinmatchup_iswinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinmatchup',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='join_tournament.tournamentplayer'),
        ),
    ]
