# Generated by Django 3.2 on 2024-04-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0004_alter_playerinmatchup_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='status',
            field=models.CharField(default='Upcoming', max_length=10),
        ),
    ]
