# Generated by Django 3.2 on 2024-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0005_matchup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='result',
            field=models.CharField(default='0 - 0', max_length=5),
        ),
        migrations.AddField(
            model_name='matchup',
            name='resultConfirmend',
            field=models.BooleanField(default=False),
        ),
    ]
