# Generated by Django 3.2 on 2024-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0006_auto_20240423_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='result',
        ),
        migrations.AddField(
            model_name='matchup',
            name='p1score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='matchup',
            name='p2score',
            field=models.IntegerField(default=-1),
        ),
    ]
