# Generated by Django 3.2 on 2024-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0007_auto_20240423_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='p1score',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='p2score',
        ),
        migrations.AddField(
            model_name='playerinmatchup',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
