# Generated by Django 3.2 on 2024-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_details', '0008_auto_20240423_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='resultConfirmend',
            new_name='resultConfirmed',
        ),
    ]
